kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: okd-cis-custom
  namespace: openshift-compliance
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'okd-cis-custom:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/pawelwojtyra/okd-docker-build.git'
      ref: main
    contextDir: /
  runPolicy: Serial

